Squashed git-subrepo master:git-subrepo 6edaf00e0 (2018-10-10 13:43:32)
url:      https://github.com/baishancloud/git-subrepo
ref:      master
sub-dir:  git-subrepo

localtag: refs/tags/_gitsubrepo/git-subrepo 6edaf00e0b6109d074e12aac633a7867f172e473

git-subrepo-dir: git-subrepo
git-subrepo-hash: 6edaf00e0b6109d074e12aac633a7867f172e473

changes: from f78a8ef20 (2017-09-27 13:16:08)
    drdr xp (3):
          auto commit
          auto commit
          auto commit
    
    张炎泼 (11):
          auto commit
          auto commit
          auto commit
          auto commit
          auto commit
          auto commit
          auto commit
          auto commit
          auto commit
          auto commit
          auto commit

diff --git a/git-subrepo b/git-subrepo
--- a/git-subrepo
+++ b/git-subrepo
@@ -215,6 +215,11 @@ git_working_root()
     git rev-parse --show-toplevel
 }
 
+git_rev_exist()
+{
+    git rev-parse --verify --quiet "$1" >/dev/null
+}
+
 git_branch_default_remote()
 {
     local branchname=$1
@@ -227,7 +232,14 @@ git_branch_default_upstream_ref()
 }
 git_branch_default_upstream()
 {
-    git_branch_default_upstream_ref "$@" | sed 's/^refs\/heads\///'
+    git rev-parse --abbrev-ref --symbolic-full-name "$1"@{upstream}
+
+    # OR
+    # git_branch_default_upstream_ref "$@" | sed 's/^refs\/heads\///'
+}
+git_branch_exist()
+{
+    git_rev_exist "refs/heads/$1"
 }
 
 git_head_branch()
@@ -285,11 +297,164 @@ git_commit_copy()
     ) || die "Can't copy commit $1"
 }
 
-git_objetct_type()
+git_object_type()
 {
     # $0 ref|hash
     # output "commit", "tree" etc
     git cat-file -t "$@" 2>/dev/null
+}
+git_object_add_by_commit_path()
+{
+    # add an blob or tree object to target_path in index
+    # the object to add is specified by commit and path
+    local target_path="$1"
+    local src_commit="$2"
+    local src_path="$3"
+
+    local src_dir="$(dirname "$src_path")/"
+    local src_name="$(basename "$src_path")"
+    local src_treeish="$(git rev-parse "$src_commit:$src_dir")"
+
+    git_object_add_by_tree_name "$target_path" "$src_treeish" "$src_name"
+
+}
+git_object_add_by_tree_name()
+{
+    # add an blob or tree object to target_path in index
+    local target_path="$1"
+    local src_treeish="$2"
+    local src_name="$3"
+
+    dd "arg: target_path: ($target_path) src_treeish: ($src_treeish) src_name: ($src_name)"
+
+    local target_dir="$(dirname $target_path)/"
+    local target_fn="$(basename $target_path)"
+    local treeish
+
+    if [ -z "$src_name" ] || [ "$src_name" = "." ] || [ "$src_name" = "./" ]; then
+        treeish="$src_treeish"
+    else
+        treeish=$(git ls-tree "$src_treeish" "$src_name" | awk '{print $3}')
+    fi
+
+    dd "hash of object to add is: $treeish"
+
+    if [ "$(git_object_type $treeish)" = "blob" ]; then
+        # the treeish imported is a file, not a dir
+        # first create a wrapper tree or replace its containing tree
+
+        dd "object to add is blob"
+
+        local dir_treeish
+        local target_dir_treeish="$(git rev-parse "HEAD:$target_dir")"
+        if [ -n "target_dir_treeish" ]; then
+            dir_treeish="$(git rev-parse "HEAD:$target_dir")"
+            dd "target dir presents: $target_dir"
+
+        else
+            dd "target dir absent"
+            dir_treeish=""
+        fi
+
+        treeish=$(git_tree_add_blob "$dir_treeish" "$target_fn" $src_treeish $src_name) || die create wrapper treeish
+        target_path="$target_dir"
+
+        dd "wrapper treeish: $treeish"
+        dd "target_path set to: $target_path"
+    else
+        dd "object to add is tree"
+    fi
+
+    git_treeish_add_to_prefix "$target_path" "$treeish"
+}
+
+git_treeish_add_to_prefix()
+{
+    local target_path="$1"
+    local treeish="$2"
+
+    dd treeish content:
+    git ls-tree $treeish
+
+    git rm "$target_path" -r --cached || dd removing target "$target_path"
+
+    if [ "$target_path" = "./" ]; then
+        git read-tree "$treeish" \
+            || die "read-tree $target_path $treeish"
+    else
+        git read-tree --prefix="$target_path" "$treeish" \
+            || die "read-tree $target_path $treeish"
+    fi
+}
+
+git_tree_add_tree()
+{
+    # output new tree hash in stdout
+    # treeish can be empty
+    local treeish="$1"
+    local target_fn="$2"
+    local item_hash="$3"
+    local item_name="$4"
+
+    {
+        if [ -n "$treeish" ]; then
+            git ls-tree "$treeish" \
+                | fgrep -v "	$item_name"
+        fi
+
+        cat "040000 tree $item_hash	$target_fn"
+    } | git mktree
+}
+git_tree_add_blob()
+{
+    # output new tree hash in stdout
+    # treeish can be empty
+    local treeish="$1"
+    local target_fn="$2"
+    local blob_treeish="$3"
+    local blob_name="$4"
+
+    {
+        if [ -n "$treeish" ]; then
+            git ls-tree "$treeish" \
+                | fgrep -v "	$target_fn"
+        fi
+
+        git ls-tree "$blob_treeish" "$blob_name" \
+            | awk -v target_fn="$target_fn" -F"	" '{print $1"	"target_fn}'
+    } | git mktree
+}
+
+git_workdir_save()
+{
+    local index_hash=$(git write-tree)
+
+    # add modified file to index and read index tree
+    git add -u
+    local working_hash=$(git write-tree)
+
+    # restore index tree
+    git read-tree $index_hash
+
+    echo $index_hash $working_hash
+}
+git_workdir_load()
+{
+    local index_hash=$1
+    local working_hash=$2
+
+    git_object_type $index_hash || die "invalid index hash: $index_hash"
+    git_object_type $working_hash || die "invalid workdir hash: $working_hash"
+
+    # First create a temp commit to restore working tree.
+    #
+    # git-read-index to index and git-reset does not work because deleted file in
+    # index does not apply to working tree.
+
+    local working_commit=$(echo "x" | git commit-tree $working_hash) || die get working commit
+    git reset --hard $working_commit || die reset to tmp commit
+    git reset --soft ORIG_HEAD || die reset to ORIG_HEAD
+    git read-tree $index_hash || die "load saved index tree from $index_hash"
 }
 
 git_copy_commit()
@@ -346,6 +511,25 @@ git_diff_ln_new()
 
 }'
 }
+
+# test:
+
+# # file to root
+# git reset --hard HEAD
+# git_object_add_by_commit_path a HEAD dist/shlib.sh
+# git status
+# # dir to root
+# git reset --hard HEAD
+# git_object_add_by_commit_path a HEAD dist
+# git status
+# # file to folder
+# git reset --hard HEAD
+# git_object_add_by_commit_path a/b/c HEAD dist/shlib.sh
+# git status
+# # dir to folder
+# git reset --hard HEAD
+# git_object_add_by_commit_path a/b/c HEAD dist
+# git status
 
 
 os_detect()
@@ -425,7 +609,11 @@ main()
         -h|--help)
             usage
             exit 0
-        ;;
+            ;;
+        init)
+            init_config
+            exit 0
+            ;;
     esac
 
 
@@ -531,26 +719,8 @@ main()
             git rm -r "$prefix" >/dev/null || die rm "$prefix"
         fi
 
-        local sub_tree
-        if [ -z "$dir" ]; then
-            sub_tree=$(git_tree_hash $tag_hash)
-        else
-            sub_tree=$(git ls-tree $tag_hash $dir| awk '{print $3}') || die "get tree-ish of $tag_hash $dir"
-        fi
-        dd "sub_tree:   $sub_tree"
-        dd "prefix:     $prefix"
-
-        if [ "$(git cat-file -t $sub_tree)" = "blob" ]; then
-            # the object imported is a file, not a dir
-
-            dd "make dir: $(dirname $prefix)"
-            mkdir -p "$(dirname $prefix)"
-            git cat-file -p $sub_tree > "$prefix"
-            git add "$prefix"
-        else
-            # load files into index at $prefix
-            git read-tree --prefix="$prefix" "$sub_tree" || die "read-tree $prefix $sub_tree"
-        fi
+        dd "add to ($prefix): from ($dir)"
+        git_object_add_by_commit_path "$prefix" "$tag_hash" "$dir" || die git_object_add_by_commit_path
 
         # remove not in index files
         git checkout -- "$prefix" || die "checkout $prefix"
@@ -598,10 +768,6 @@ main()
 
         git merge --ff-only --no-edit --commit $commit
 
-        # git subtree merge --squash \
-        #     --message="Merge squashed $url $ref" \
-        #     --prefix "$prefix" "$localtag" || die merge
-
     done<".gitsubrepo_refs"
 
     while read a b c localtag dir; do
@@ -610,6 +776,41 @@ main()
     done<".gitsubrepo_refs"
 
     rm .gitsubrepo_refs
+}
+
+init_config()
+{
+    local root=$(git_working_root)
+    [ "x$root" = "x" ] && die 'looking for git repo root'
+
+    (
+    cd $root
+
+    if [ -f .gitsubrepo ]; then
+        echo ".gitsubrepo already exists"
+        return 0
+    fi
+
+    cat >.gitsubrepo <<-END
+	[ remote_suffix: .git ]
+	[ remote: https://github.com/ ]
+
+	[ base: ]
+	git-subrepo      baishancloud/git-subrepo       master   git-subrepo
+
+	[ base: deps ]
+	pykit            baishancloud/pykit             master
+
+
+	# git-subrepo
+	#   for maintaining sub git repo
+	#   https://github.com/baishancloud/git-subrepo
+	END
+
+    vim .gitsubrepo
+    git add .gitsubrepo
+    echo "git commit to persistent .gitsubrepo config"
+    )
 }
 
 find_latest_squash()
